# Generated by Django 2.0.1 on 2018-01-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybearsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroups',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='studygroups',
            name='pending_requests',
        ),
        migrations.AddField(
            model_name='studygroups',
            name='members',
            field=models.ManyToManyField(to='studybearsapp.User'),
        ),
    ]
