# Generated by Django 2.0.5 on 2018-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybearsapp', '0005_profile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroups',
            name='date_times',
        ),
        migrations.RemoveField(
            model_name='studygroups',
            name='size',
        ),
        migrations.AddField(
            model_name='studygroups',
            name='date_time',
            field=models.DateTimeField(default='2018-1-1 00:00'),
        ),
        migrations.AddField(
            model_name='studygroups',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studygroups',
            name='study_strategies',
            field=models.TextField(default='', max_length=500),
        ),
    ]
