# Generated by Django 2.0.5 on 2018-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybearsapp', '0006_auto_20180611_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroups',
            name='date_time',
            field=models.DateTimeField(default='2018-1-1 00:00'),
        ),
    ]
