# Generated by Django 2.0.5 on 2018-06-11 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybearsapp', '0008_auto_20180611_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroups',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
