# Generated by Django 2.0.5 on 2018-06-28 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studybearsapp', '0009_auto_20180611_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroups',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='studygroups',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='studygroups',
            name='location',
        ),
        migrations.AddField(
            model_name='studygroups',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
